Update to Nuxt 3.8
nypublicradio/gothamist-vue3 pull request #327
Opened 2023-10-19 18:52 UTC by walsh9

- Update to Nuxt 3.8
- Update to Node 18

2023-10-19 18:52 UTC, kimlarocca approved these changes
💪💪💪

2023-10-24 14:59 UTC, skacula requested changes
I've added suggestions to change the version to a pinned version. This is the version being used for wnyc-vue3 project.

2023-10-24 14:59 UTC, skacula commented on .circleci/config.yml
> +      - image: node:18-slim
Please update the image to use the following version: 18.18.2-slim

2023-10-24 14:59 UTC, skacula commented on Dockerfile
> +FROM node:18-slim as app
```suggestion
FROM node:18.18.2-slim as app
```

2023-10-24 14:59 UTC, skacula commented on Dockerfile
> +FROM node:18 as build
```suggestion
FROM node:18.18.2 as build
```

2023-10-24 14:59 UTC, skacula commented on .circleci/config.yml
> +      - image: node:18-slim
```suggestion
      - image: node:18.18.2-slim
```

2023-10-24 14:59 UTC, skacula commented on squash_Dockerfile
> +FROM node:18 as build
```suggestion
FROM node:18.18.2 as build
```

2023-10-24 14:59 UTC, skacula commented on squash_Dockerfile
> +FROM node:18-slim as app
```suggestion
FROM node:18.18.2-slim as app
```

2023-10-25 17:32 UTC, skacula approved these changes
LGTM!

2023-10-26 13:59 UTC, merged